import type { DemoScenario } from "./demoScenarioSchema"

export const demoScenarios: DemoScenario[] = [
  {
    id: "directory",
    path: "/demo",
    group: "Directory",
    label: "All screens",
    detail: "Jump to any screen or variant",
  },
  {
    id: "loading",
    path: "/demo/loading",
    group: "App",
    label: "Loading",
    detail: "Initial sign-in bootstrap",
  },
  {
    id: "continuing",
    path: "/demo/continuing",
    group: "App",
    label: "Continuing",
    detail: "Redirect after a completed sign-in",
  },
  {
    id: "fatal",
    path: "/demo/fatal",
    group: "App",
    label: "Unable to continue",
    detail: "Fatal initialization error",
  },
  {
    id: "chooser",
    path: "/demo/chooser",
    group: "Chooser",
    label: "Method chooser",
    detail: "All primary methods, no recent accounts",
  },
  {
    id: "chooser-recent",
    path: "/demo/chooser/recent-accounts",
    group: "Chooser",
    label: "Chooser with recent accounts",
    detail: "Recent accounts plus methods",
  },
  {
    id: "email-otp-email",
    path: "/demo/email-otp",
    group: "Email OTP",
    label: "Enter email",
    detail: "Start email-code sign-in",
  },
  {
    id: "email-otp-code",
    path: "/demo/email-otp/code",
    group: "Email OTP",
    label: "Enter code",
    detail: "Code sent, ready to verify",
  },
  {
    id: "password",
    path: "/demo/password",
    group: "Password",
    label: "Password sign-in",
    detail: "Identifier and password",
  },
  {
    id: "password-error",
    path: "/demo/password/error",
    group: "Password",
    label: "Password error",
    detail: "Invalid credentials message",
  },
  {
    id: "password-mfa",
    path: "/demo/password/mfa-required",
    group: "Password",
    label: "Password MFA placeholder",
    detail: "Legacy MFA-required fallback",
  },
  {
    id: "password-change",
    path: "/demo/password/change-required",
    group: "Password",
    label: "Change required",
    detail: "Policy-required password change",
  },
  {
    id: "password-change-expired",
    path: "/demo/password/change-required/expired",
    group: "Password",
    label: "Password expired",
    detail: "Expired-password change",
  },
  {
    id: "passkey",
    path: "/demo/passkey",
    group: "Passkey",
    label: "Passkey sign-in",
    detail: "Supported browser, identifier first",
  },
  {
    id: "passkey-unsupported",
    path: "/demo/passkey/unsupported",
    group: "Passkey",
    label: "Passkey unsupported",
    detail: "Browser without WebAuthn",
  },
  {
    id: "passkey-mfa",
    path: "/demo/passkey/mfa-required",
    group: "Passkey",
    label: "Passkey MFA placeholder",
    detail: "Legacy MFA-required fallback",
  },
  {
    id: "idp",
    path: "/demo/idp",
    group: "Identity provider",
    label: "Continue with Google",
    detail: "Start an external provider",
  },
  {
    id: "idp-failure",
    path: "/demo/idp/failure",
    group: "Identity provider",
    label: "Provider failure",
    detail: "Sign-in was not completed",
  },
  {
    id: "idp-account-not-found",
    path: "/demo/idp/account-not-found",
    group: "Identity provider",
    label: "Account not found",
    detail: "No linked ZITADEL account",
  },
  {
    id: "idp-linking-failed",
    path: "/demo/idp/linking-failed",
    group: "Identity provider",
    label: "Linking failed",
    detail: "Could not link the account",
  },
  {
    id: "idp-registration-failed",
    path: "/demo/idp/registration-failed",
    group: "Identity provider",
    label: "Registration failed",
    detail: "Could not register the account",
  },
  {
    id: "mfa-select",
    path: "/demo/mfa",
    group: "MFA",
    label: "Choose a factor",
    detail: "Select among enrolled methods",
  },
  {
    id: "mfa-enroll",
    path: "/demo/mfa/enroll",
    group: "MFA",
    label: "Set up a factor",
    detail: "Required enrollment chooser",
  },
  {
    id: "mfa-skip-optional",
    path: "/demo/mfa/optional",
    group: "MFA",
    label: "Optional setup",
    detail: "Skip or enroll a method",
  },
  {
    id: "mfa-skip-satisfied",
    path: "/demo/mfa/satisfied",
    group: "MFA",
    label: "Already satisfied",
    detail: "Policy already met",
  },
  {
    id: "mfa-fallback",
    path: "/demo/mfa/fallback",
    group: "MFA",
    label: "Native fallback",
    detail: "Continue in ZITADEL",
  },
  {
    id: "mfa-loading",
    path: "/demo/mfa/loading",
    group: "MFA",
    label: "Loading options",
    detail: "Fetching 2-step choices",
  },
  {
    id: "mfa-retry",
    path: "/demo/mfa/retry",
    group: "MFA",
    label: "Options failed",
    detail: "Retry loading options",
  },
  {
    id: "mfa-totp",
    path: "/demo/mfa/totp",
    group: "MFA",
    label: "Authenticator code",
    detail: "Verify a TOTP code",
  },
  {
    id: "mfa-email-otp",
    path: "/demo/mfa/email-otp",
    group: "MFA",
    label: "Send email code",
    detail: "Challenge start for email OTP",
  },
  {
    id: "mfa-email-otp-code",
    path: "/demo/mfa/email-otp/code",
    group: "MFA",
    label: "Enter email code",
    detail: "Pending email OTP verification",
  },
  {
    id: "mfa-email-otp-enroll",
    path: "/demo/mfa/email-otp/enroll",
    group: "MFA",
    label: "Set up email codes",
    detail: "Enroll email OTP",
  },
  {
    id: "mfa-sms-otp",
    path: "/demo/mfa/sms-otp",
    group: "MFA",
    label: "Send SMS code",
    detail: "Challenge start for SMS OTP",
  },
  {
    id: "mfa-u2f",
    path: "/demo/mfa/u2f",
    group: "MFA",
    label: "Security key",
    detail: "Verify with a hardware key",
  },
  {
    id: "mfa-u2f-unsupported",
    path: "/demo/mfa/u2f/unsupported",
    group: "MFA",
    label: "Security key unsupported",
    detail: "Browser without WebAuthn",
  },
  {
    id: "mfa-passkey",
    path: "/demo/mfa/passkey",
    group: "MFA",
    label: "Passkey factor",
    detail: "Verify with an enrolled passkey",
  },
  {
    id: "mfa-totp-enroll",
    path: "/demo/mfa/totp-enroll",
    group: "MFA",
    label: "Set up authenticator",
    detail: "Start TOTP enrollment",
  },
  {
    id: "mfa-totp-unavailable",
    path: "/demo/mfa/totp-enroll/unavailable",
    group: "MFA",
    label: "Authenticator unavailable",
    detail: "Enrollment cannot be resumed",
  },
  {
    id: "mfa-webauthn-enroll",
    path: "/demo/mfa/webauthn-enroll",
    group: "MFA",
    label: "Set up a passkey",
    detail: "Register a new passkey",
  },
  {
    id: "mfa-u2f-enroll",
    path: "/demo/mfa/u2f-enroll",
    group: "MFA",
    label: "Set up a security key",
    detail: "Register a hardware key",
  },
  {
    id: "mfa-webauthn-unavailable",
    path: "/demo/mfa/webauthn-enroll/unavailable",
    group: "MFA",
    label: "Passkey setup unavailable",
    detail: "Registration cannot be resumed",
  },
  {
    id: "recovery-request",
    path: "/demo/password/forgot",
    group: "Recovery",
    label: "Request reset",
    detail: "Enter email for a reset link",
  },
  {
    id: "recovery-sent",
    path: "/demo/password/forgot/sent",
    group: "Recovery",
    label: "Reset link sent",
    detail: "Check-your-email confirmation",
  },
  {
    id: "recovery-fatal",
    path: "/demo/password/forgot/unavailable",
    group: "Recovery",
    label: "Recovery unavailable",
    detail: "Bootstrap failed",
  },
  {
    id: "recovery-loading",
    path: "/demo/password/forgot/loading",
    group: "Recovery",
    label: "Loading recovery",
    detail: "Recovery bootstrap spinner",
  },
  {
    id: "reset",
    path: "/demo/password/reset",
    group: "Recovery",
    label: "Choose a new password",
    detail: "Valid reset-link form",
  },
  {
    id: "reset-complete",
    path: "/demo/password/reset/complete",
    group: "Recovery",
    label: "Password changed",
    detail: "Reset finished successfully",
  },
  {
    id: "reset-invalid",
    path: "/demo/password/reset/invalid",
    group: "Recovery",
    label: "Invalid reset link",
    detail: "Expired or already used",
  },
  {
    id: "reset-loading",
    path: "/demo/password/reset/loading",
    group: "Recovery",
    label: "Checking reset link",
    detail: "Reset bootstrap spinner",
  },
  {
    id: "unsupported",
    path: "/demo/unsupported",
    group: "Fallback",
    label: "Unsupported method",
    detail: "Continue in ZITADEL",
  },
]
